name: CI — Build, Sentry Release & Lighthouse

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      SENTRY_ORG: iberico-experience
      SENTRY_PROJECT: javascript-nextjs
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        run: npm run build

      - name: Create Sentry release (if token present)
        run: |
          if [ -z "$SENTRY_AUTH_TOKEN" ]; then
            echo "SENTRY_AUTH_TOKEN not set; skipping sentry release."
            exit 0
          fi
          echo "Creating release from GITHUB_SHA"
          RELEASE=${GITHUB_SHA}
          npm exec -- sentry-cli releases new "$RELEASE" --org $SENTRY_ORG --project $SENTRY_PROJECT
          npm exec -- sentry-cli releases files "$RELEASE" upload-sourcemaps .next --org $SENTRY_ORG --project $SENTRY_PROJECT --rewrite --ext map --ext js
          npm exec -- sentry-cli releases finalize "$RELEASE" --org $SENTRY_ORG --project $SENTRY_PROJECT

  lighthouse:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps || true
      - name: Run Lighthouse (local)
        run: |
          echo "Skipping full Lighthouse run in CI where public URL not guaranteed; consider running externally or using Vercel preview URL."
