name: Lighthouse CI

on:
  push:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Start server
        run: npx next start -p 3000 &
      - name: Wait for server
        run: npx wait-on http://localhost:3000
      - name: Run Lighthouse CI
        run: |
          npx -y lhci autorun --upload.target=temporary-public-storage

      - name: Upload Sentry sourcemaps (optional)
        if: secrets.SENTRY_AUTH_TOKEN != ''
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          npm i -g @sentry/cli
          sentry-cli --version
          export SENTRY_RELEASE=$(node -e "console.log(require('./package.json').version || 'unknown')")
          sentry-cli releases new $SENTRY_RELEASE || true
          sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps .next --rewrite || true
