name: Perf & Sentry Upload

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        env:
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_RELEASE: ${{ github.sha }}
        run: |
          npm run build

      - name: Create Sentry release and upload sourcemaps
        if: ${{ secrets.SENTRY_AUTH_TOKEN }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: iberico-experience
          SENTRY_PROJECT: javascript-nextjs
        run: |
          RELEASE=${{ github.sha }}
          sentry-cli releases new $RELEASE --org $SENTRY_ORG --project $SENTRY_PROJECT || true
          sentry-cli releases files $RELEASE upload-sourcemaps .next --org $SENTRY_ORG --project $SENTRY_PROJECT --rewrite || true
          sentry-cli releases finalize $RELEASE --org $SENTRY_ORG --project $SENTRY_PROJECT || true

  lighthouse:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lighthouse (node)
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://agencia-viajes2-frjhdxuhi-theibericoexperience-devs-projects.vercel.app/
          budgetPath: .lighthouse/budget.json
